services:
  - type: worker
    name: musicplayer
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python3 main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.21
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: SESSION
        sync: false
      - key: SUDOERS
        sync: false
      - key: PREFIX
        value: "! /"
      - key: LANGUAGE
        value: en
      - key: STREAM_MODE
        value: audio
